# Generated by Django 4.1.8 on 2024-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confidence", models.FloatField(blank=True, default=0.8, null=True)),
            ],
        ),
    ]
