# Generated by Django 4.1.8 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_advice"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="advice",
            field=models.TextField(blank=True, null=True),
        ),
    ]
